import Head from "next/head";

import HomeBackround from "../Components/Dicover/HomeBackround";
import Feature from "../Components/Feature/Feature";
import Footer from "../Components/Footer/Footer";
import Form from "../Components/Form/Form";
import Header from "../Components/Header/Header";
import Human_Picture from "../Components/HumanPicture/Human_Picture";
import Info from "../Components/Info/Info";
import Picture_Brind from "../Components/picture_brind/Picture_Brind";
import Products from "../Components/Products/Products";
import Shop_Brend from "../Components/Shop_brend/Shop_Brend";
import Skinn_Blog from "../Components/Skinn_Blog/Skinn_Blog";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <HomeBackround />
        <Shop_Brend />
        <Picture_Brind />
        <Products />
        <Feature />
        <Info />
        <Human_Picture />
        <Skinn_Blog />
        <Form />
        <Footer />
      </main>
    </div>
  );
}
